# ADD USER
POST http://localhost:4000/user/adduser
Content-Type: application/json

{
    "f_name":"amit",
    "l_name":"s",
    "address":"sangli",
    "email":"a@s.com",
    "contact":"9876543999",
    "password":"hello"
}

###

# LOGIN
POST http://localhost:4000/user/login
Content-Type: application/json

{   
    "email":"a@s.com",  
    "password":"hello"
}
###

# PRODUCTS
# Add product
POST http://localhost:4000/product/addproduct
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU0NDRiOGFiLTZiZDEtNDZmOS04MjFkLTYyZjZhNGUzMmZlMyIsImZpcnN0X25hbWUiOiJhbWl0IiwibGFzdF9uYW1lIjoicyIsImVtYWlsIjoiYUBzLmNvbSIsImlhdCI6MTY5MjYxMjcxNX0.Bv-sJVVQjoJY_Wbu8aKRPzkHgj1c65hz1dujOsCDwK0

{
    "name":"Laptop4",
    "description":"8GB RAM, 1TB SSD, RTX3050",
    "amount":9000,    
    "pictures":["NA"],
    "status":1   
}

###
# GET Products list
GET http://localhost:4000/product/products

###
#Delete 
DELETE http://localhost:4000/product/deleteproduct/64dcbbfe5510beacacbe6e11
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU4NzM0YzQ4LWFhOTQtNDE0My04Mzc0LTc1ZDkyZWNhNGJkMiIsImZpcnN0X25hbWUiOiJhbWl0MiIsImxhc3RfbmFtZSI6InMiLCJlbWFpbCI6ImFAc29vLmNvbSIsImlhdCI6MTY5MjE4Njc0Mn0.uogBYoJ7YAhEA-5vcoBBwtD8w3NjOG7vrIaV6GcaiU0


###

#update

PATCH  http://localhost:4000/product/updateproduct/64dcbbfe5510beacacbe6e11
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU4NzM0YzQ4LWFhOTQtNDE0My04Mzc0LTc1ZDkyZWNhNGJkMiIsImZpcnN0X25hbWUiOiJhbWl0MiIsImxhc3RfbmFtZSI6InMiLCJlbWFpbCI6ImFAc29vLmNvbSIsImlhdCI6MTY5MjE4Njc0Mn0.uogBYoJ7YAhEA-5vcoBBwtD8w3NjOG7vrIaV6GcaiU0

{
    "name":"Laptop",
    "description":"16GB RAM, 1TB SSD, RTX2070TI",
    "amount":790000,    
    "pictures":["NA"],
    "status":1     
}

###

#Orders

# ADD ORDER
POST http://localhost:4000/order/addorder
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU0NDRiOGFiLTZiZDEtNDZmOS04MjFkLTYyZjZhNGUzMmZlMyIsImZpcnN0X25hbWUiOiJhbWl0IiwibGFzdF9uYW1lIjoicyIsImVtYWlsIjoiYUBzLmNvbSIsImlhdCI6MTY5MjYxMjcxNX0.Bv-sJVVQjoJY_Wbu8aKRPzkHgj1c65hz1dujOsCDwK0

{
    "items":["64dcb82c899633050854cb42","64dc9d1df0a409459ca987f6","64dcb8fe899633050854cb4a"],    
    "total_amount":303000    
}

###

# GET order list
GET http://localhost:4000/order/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU0NDRiOGFiLTZiZDEtNDZmOS04MjFkLTYyZjZhNGUzMmZlMyIsImZpcnN0X25hbWUiOiJhbWl0IiwibGFzdF9uYW1lIjoicyIsImVtYWlsIjoiYUBzLmNvbSIsImlhdCI6MTY5MjYxMjcxNX0.Bv-sJVVQjoJY_Wbu8aKRPzkHgj1c65hz1dujOsCDwK0


###
#Delete 
DELETE http://localhost:4000/order/deleteorder/64e3398ab7efbaa1bb2cb3d6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU0NDRiOGFiLTZiZDEtNDZmOS04MjFkLTYyZjZhNGUzMmZlMyIsImZpcnN0X25hbWUiOiJhbWl0IiwibGFzdF9uYW1lIjoicyIsImVtYWlsIjoiYUBzLmNvbSIsImlhdCI6MTY5MjYxMjcxNX0.Bv-sJVVQjoJY_Wbu8aKRPzkHgj1c65hz1dujOsCDwK0
###

#update

PATCH  http://localhost:4000/order/updateorder/64e33a50b7efbaa1bb2cb3db
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU0NDRiOGFiLTZiZDEtNDZmOS04MjFkLTYyZjZhNGUzMmZlMyIsImZpcnN0X25hbWUiOiJhbWl0IiwibGFzdF9uYW1lIjoicyIsImVtYWlsIjoiYUBzLmNvbSIsImlhdCI6MTY5MjYxMjcxNX0.Bv-sJVVQjoJY_Wbu8aKRPzkHgj1c65hz1dujOsCDwK0

{
    "items":["64dc9d1df0a409459ca987f6"],    
    "total_amount":125000 
    
}